version: "3.9"
services:
  grpc:
    container_name: grpcservicedev
    build:      
      dockerfile: Dockerfile   
      target: grpcserver
    expose:
      - "9000"  
    networks:
      - poc-network
  rest:
    container_name: restservicedev
    build:
      dockerfile: Dockerfile      
      target: restserver
    ports:
      - "8000:8000"
    networks:
      - poc-network
    tty:
      true
    depends_on:
      - grpc

networks:
  poc-network: {}
    
